name: discogan_eval

channels:
    - defaults
    - conda-forge

dependencies:
    - python=3.10
    - h5py
    - configargparse
    - pip==23.3.1
    
    - pip:
        - tqdm
        - librosa
        - matplotlib
        - PyYAML
        